# Generated by Django 5.0.1 on 2024-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='decription',
            field=models.CharField(default='goaldescription', max_length=2000),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(default='goalname', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
