# Generated by Django 5.0.1 on 2024-04-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='author',
        ),
    ]
