# Generated by Django 5.0.1 on 2024-05-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_goal_decription_alter_goal_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='decription',
            new_name='description',
        ),
    ]
