# Generated by Django 5.0.1 on 2024-06-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_goal_status_alter_task_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
